CREATE TABLE application_train (
  SK_ID_CURR                   int,
  TARGET                       int,
  NAME_CONTRACT_TYPE           varchar(255),
  CODE_GENDER                  varchar(255),
  FLAG_OWN_CAR                 varchar(255),
  FLAG_OWN_REALTY              varchar(255),
  CNT_CHILDREN                 int,
  AMT_INCOME_TOTAL             double(20, 10),
  AMT_CREDIT                   double(20, 10),
  AMT_ANNUITY                  double(20, 10),
  AMT_GOODS_PRICE              double(20, 10),
  NAME_TYPE_SUITE              varchar(255),
  NAME_INCOME_TYPE             varchar(255),
  NAME_EDUCATION_TYPE          varchar(255),
  NAME_FAMILY_STATUS           varchar(255),
  NAME_HOUSING_TYPE            varchar(255),
  REGION_POPULATION_RELATIVE   double(20, 10),
  DAYS_BIRTH                   int,
  DAYS_EMPLOYED                int,
  DAYS_REGISTRATION            double(20, 10),
  DAYS_ID_PUBLISH              int,
  OWN_CAR_AGE                  double(20, 10),
  FLAG_MOBIL                   int,
  FLAG_EMP_PHONE               int,
  FLAG_WORK_PHONE              int,
  FLAG_CONT_MOBILE             int,
  FLAG_PHONE                   int,
  FLAG_EMAIL                   int,
  OCCUPATION_TYPE              varchar(255),
  CNT_FAM_MEMBERS              double(20, 10),
  REGION_RATING_CLIENT         int,
  REGION_RATING_CLIENT_W_CITY  int,
  WEEKDAY_APPR_PROCESS_START   varchar(255),
  HOUR_APPR_PROCESS_START      int,
  REG_REGION_NOT_LIVE_REGION   int,
  REG_REGION_NOT_WORK_REGION   int,
  LIVE_REGION_NOT_WORK_REGION  int,
  REG_CITY_NOT_LIVE_CITY       int,
  REG_CITY_NOT_WORK_CITY       int,
  LIVE_CITY_NOT_WORK_CITY      int,
  ORGANIZATION_TYPE            varchar(255),
  EXT_SOURCE_1                 double(20, 10),
  EXT_SOURCE_2                 double(20, 10),
  EXT_SOURCE_3                 double(20, 10),
  APARTMENTS_AVG               double(20, 10),
  BASEMENTAREA_AVG             double(20, 10),
  YEARS_BEGINEXPLUATATION_AVG  double(20, 10),
  YEARS_BUILD_AVG              double(20, 10),
  COMMONAREA_AVG               double(20, 10),
  ELEVATORS_AVG                double(20, 10),
  ENTRANCES_AVG                double(20, 10),
  FLOORSMAX_AVG                double(20, 10),
  FLOORSMIN_AVG                double(20, 10),
  LANDAREA_AVG                 double(20, 10),
  LIVINGAPARTMENTS_AVG         double(20, 10),
  LIVINGAREA_AVG               double(20, 10),
  NONLIVINGAPARTMENTS_AVG      double(20, 10),
  NONLIVINGAREA_AVG            double(20, 10),
  APARTMENTS_MODE              double(20, 10),
  BASEMENTAREA_MODE            double(20, 10),
  YEARS_BEGINEXPLUATATION_MODE double(20, 10),
  YEARS_BUILD_MODE             double(20, 10),
  COMMONAREA_MODE              double(20, 10),
  ELEVATORS_MODE               double(20, 10),
  ENTRANCES_MODE               double(20, 10),
  FLOORSMAX_MODE               double(20, 10),
  FLOORSMIN_MODE               double(20, 10),
  LANDAREA_MODE                double(20, 10),
  LIVINGAPARTMENTS_MODE        double(20, 10),
  LIVINGAREA_MODE              double(20, 10),
  NONLIVINGAPARTMENTS_MODE     double(20, 10),
  NONLIVINGAREA_MODE           double(20, 10),
  APARTMENTS_MEDI              double(20, 10),
  BASEMENTAREA_MEDI            double(20, 10),
  YEARS_BEGINEXPLUATATION_MEDI double(20, 10),
  YEARS_BUILD_MEDI             double(20, 10),
  COMMONAREA_MEDI              double(20, 10),
  ELEVATORS_MEDI               double(20, 10),
  ENTRANCES_MEDI               double(20, 10),
  FLOORSMAX_MEDI               double(20, 10),
  FLOORSMIN_MEDI               double(20, 10),
  LANDAREA_MEDI                double(20, 10),
  LIVINGAPARTMENTS_MEDI        double(20, 10),
  LIVINGAREA_MEDI              double(20, 10),
  NONLIVINGAPARTMENTS_MEDI     double(20, 10),
  NONLIVINGAREA_MEDI           double(20, 10),
  FONDKAPREMONT_MODE           double(20, 10),
  HOUSETYPE_MODE               double(20, 10),
  TOTALAREA_MODE               double(20, 10),
  WALLSMATERIAL_MODE           double(20, 10),
  EMERGENCYSTATE_MODE          double(20, 10),
  OBS_30_CNT_SOCIAL_CIRCLE     double(20, 10),
  DEF_30_CNT_SOCIAL_CIRCLE     double(20, 10),
  OBS_60_CNT_SOCIAL_CIRCLE     double(20, 10),
  DEF_60_CNT_SOCIAL_CIRCLE     double(20, 10),
  DAYS_LAST_PHONE_CHANGE       double(20, 10),
  FLAG_DOCUMENT_2              int,
  FLAG_DOCUMENT_3              int,
  FLAG_DOCUMENT_4              int,
  FLAG_DOCUMENT_5              int,
  FLAG_DOCUMENT_6              int,
  FLAG_DOCUMENT_7              int,
  FLAG_DOCUMENT_8              int,
  FLAG_DOCUMENT_9              int,
  FLAG_DOCUMENT_10             int,
  FLAG_DOCUMENT_11             int,
  FLAG_DOCUMENT_12             int,
  FLAG_DOCUMENT_13             int,
  FLAG_DOCUMENT_14             int,
  FLAG_DOCUMENT_15             int,
  FLAG_DOCUMENT_16             int,
  FLAG_DOCUMENT_17             int,
  FLAG_DOCUMENT_18             int,
  FLAG_DOCUMENT_19             int,
  FLAG_DOCUMENT_20             int,
  FLAG_DOCUMENT_21             int,
  AMT_REQ_CREDIT_BUREAU_HOUR   double(20, 10),
  AMT_REQ_CREDIT_BUREAU_DAY    double(20, 10),
  AMT_REQ_CREDIT_BUREAU_WEEK   double(20, 10),
  AMT_REQ_CREDIT_BUREAU_MON    double(20, 10),
  AMT_REQ_CREDIT_BUREAU_QRT    double(20, 10),
  AMT_REQ_CREDIT_BUREAU_YEAR   double(20, 10)
);

CREATE TABLE bureau (
  SK_ID_CURR             INT,
  SK_ID_BUREAU           INT,
  CREDIT_ACTIVE          varchar(255),
  CREDIT_CURRENCY        varchar(255),
  DAYS_CREDIT            int,
  CREDIT_DAY_OVERDUE     int,
  DAYS_CREDIT_ENDDATE    double(20, 10),
  DAYS_ENDDATE_FACT      double(20, 10),
  AMT_CREDIT_MAX_OVERDUE double(20, 10),
  CNT_CREDIT_PROLONG     int,
  AMT_CREDIT_SUM         double(20, 10),
  AMT_CREDIT_SUM_DEBT    double(20, 10),
  AMT_CREDIT_SUM_LIMIT   double(20, 10),
  AMT_CREDIT_SUM_OVERDUE double(20, 10),
  CREDIT_TYPE            varchar(255),
  DAYS_CREDIT_UPDATE     int,
  AMT_ANNUITY            double(20, 10)
);

CREATE TABLE bureau_balance (
  SK_ID_BUREAU   INT,
  MONTHS_BALANCE INT,
  STATUS         VARCHAR(255)

);

CREATE TABLE credit_card_balance (
  SK_ID_PREV                 int,
  SK_ID_CURR                 int,
  MONTHS_BALANCE             int,
  AMT_BALANCE                double(20, 10),
  AMT_CREDIT_LIMIT_ACTUAL    int,
  AMT_DRAWINGS_ATM_CURRENT   double(20, 10),
  AMT_DRAWINGS_CURRENT       double(20, 10),
  AMT_DRAWINGS_OTHER_CURRENT double(20, 10),
  AMT_DRAWINGS_POS_CURRENT   double(20, 10),
  AMT_INST_MIN_REGULARITY    double(20, 10),
  AMT_PAYMENT_CURRENT        double(20, 10),
  AMT_PAYMENT_TOTAL_CURRENT  double(20, 10),
  AMT_RECEIVABLE_PRINCIPAL   double(20, 10),
  AMT_RECIVABLE              double(20, 10),
  AMT_TOTAL_RECEIVABLE       double(20, 10),
  CNT_DRAWINGS_ATM_CURRENT   double(20, 10),
  CNT_DRAWINGS_CURRENT       int,
  CNT_DRAWINGS_OTHER_CURRENT double(20, 10),
  CNT_DRAWINGS_POS_CURRENT   double(20, 10),
  CNT_INSTALMENT_MATURE_CUM  double(20, 10),
  NAME_CONTRACT_STATUS       varchar(255),
  SK_DPD                     int,
  SK_DPD_DEF                 int
);

CREATE TABLE installments_payments (
  SK_ID_PREV             int,
  SK_ID_CURR             int,
  NUM_INSTALMENT_VERSION double(20, 10),
  NUM_INSTALMENT_NUMBER  int,
  DAYS_INSTALMENT        double(20, 10),
  DAYS_ENTRY_PAYMENT     double(20, 10),
  AMT_INSTALMENT         double(20, 10),
  AMT_PAYMENT            double(20, 10)
);

CREATE TABLE pos_cash_balance (
  SK_ID_PREV            int,
  SK_ID_CURR            int,
  MONTHS_BALANCE        int,
  CNT_INSTALMENT        varchar(255),
  CNT_INSTALMENT_FUTURE varchar(255),
  NAME_CONTRACT_STATUS  varchar(255),
  SK_DPD                int,
  SK_DPD_DEF            int
);

CREATE TABLE previous_application (
  SK_ID_PREV                  int,
  SK_ID_CURR                  int,
  NAME_CONTRACT_TYPE          varchar(255),
  AMT_ANNUITY                 double(20, 10),
  AMT_APPLICATION             double(20, 10),
  AMT_CREDIT                  double(20, 10),
  AMT_DOWN_PAYMENT            double(20, 10),
  AMT_GOODS_PRICE             double(20, 10),
  WEEKDAY_APPR_PROCESS_START  varchar(255),
  HOUR_APPR_PROCESS_START     int,
  FLAG_LAST_APPL_PER_CONTRACT varchar(255),
  NFLAG_LAST_APPL_IN_DAY      int,
  RATE_DOWN_PAYMENT           double(20, 10),
  RATE_INTEREST_PRIMARY       double(20, 10),
  RATE_INTEREST_PRIVILEGED    double(20, 10),
  NAME_CASH_LOAN_PURPOSE      varchar(255),
  NAME_CONTRACT_STATUS        varchar(255),
  DAYS_DECISION               int,
  NAME_PAYMENT_TYPE           varchar(255),
  CODE_REJECT_REASON          varchar(255),
  NAME_TYPE_SUITE             varchar(255),
  NAME_CLIENT_TYPE            varchar(255),
  NAME_GOODS_CATEGORY         varchar(255),
  NAME_PORTFOLIO              varchar(255),
  NAME_PRODUCT_TYPE           varchar(255),
  CHANNEL_TYPE                varchar(255),
  SELLERPLACE_AREA            int,
  NAME_SELLER_INDUSTRY        varchar(255),
  CNT_PAYMENT                 double(20, 10),
  NAME_YIELD_GROUP            varchar(255),
  PRODUCT_COMBINATION         varchar(255),
  DAYS_FIRST_DRAWING          double(20, 10),
  DAYS_FIRST_DUE              double(20, 10),
  DAYS_LAST_DUE_1ST_VERSION   double(20, 10),
  DAYS_LAST_DUE               double(20, 10),
  DAYS_TERMINATION            double(20, 10),
  NFLAG_INSURED_ON_APPROVAL   double(20, 10)
);
